"""Модуль локализации для arqParse."""

class Translator:
    _instance = None
    
    LANGUAGES = {
        'ru': {
            'app_title': 'arqParse',
            'app_subtitle': 'Тестирование VPN конфигов',
            'login': 'Логин',
            'password': 'Пароль',
            'tab_login': 'Вход',
            'tab_register': 'Регистрация',
            'btn_login': 'Войти',
            'btn_register': 'Зарегистрироваться',
            'btn_guest': 'Войти как гость',
            'by_author': 'от ',
            'subscription': 'Подписка',
            'sub_url_hint': 'Ссылка появится после входа',
            'btn_copy_sub': 'Скопировать ссылку',
            'bot_link_prefix': 'Применить тг прокси можно в боте ',
            'btn_start_test': 'Начать тест',
            'btn_adv_settings': 'Дополнительные настройки',
            'btn_hide_settings': 'Скрыть настройки',
            'select_tasks': 'Выбрать задачи',
            'btn_download': 'Скачать',
            'btn_results': 'Результаты',
            'btn_skip': 'Пропустить',
            'btn_stop': 'Остановить',
            'progress': 'Прогресс:',
            'ready': 'Готов к работе',
            'event_log': 'Журнал событий',
            'log_started': 'arqParse запущен',
            'settings': 'Настройки',
            'settings_general': 'Общие',
            'auto_update': 'Автообновление источников',
            'language': 'Язык',
            'btn_save': 'Сохранить',
            'btn_reset': 'Восстановить по умолчанию',
            'categories': 'Категории',
            'btn_add_category': '+ Добавить категорию',
            'cat_name': 'Название категории',
            'cat_type': 'Тип:',
            'cat_sources': 'Источники (URL):',
            'btn_add_url': '+ Добавить URL',
            'cat_target': 'Целевой URL',
            'cat_max_ping': 'Макс.пинг:',
            'cat_min_count': 'Мин.кол-во:',
            'cat_profile': 'Имя профиля',
            'btn_delete': 'Удалить',
            'msg_saved': 'Сохранено',
            'msg_restored': 'Настройки восстановлены',
            'msg_logged_out': 'Вы вышли из системы',
            'msg_guest_active': 'Режим гостя активирован',
            'msg_login_min': 'Логин минимум 3 символа',
            'msg_pass_min': 'Пароль минимум 6 символов',
            'msg_connecting': 'Подключение',
            'msg_registering': 'Регистрация',
            'msg_server_offline': 'Сервер недоступен',
            'msg_auth_success': 'Успешный вход',
            'msg_auth_error': 'Ошибка:',
            'msg_sub_copied': 'Скопировано',
            'msg_sub_no_url': 'Ссылка недоступна',
            'msg_sub_guest': 'Функция недоступна для гостей',
            'msg_op_running': 'Операция уже выполняется',
            'msg_no_tasks': 'Выберите хотя бы одну задачу',
            'msg_test_started': 'Запуск...',
            'msg_testing': 'Тестирование:',
            'msg_checking_configs': 'Проверка актуальности конфигов...',
            'msg_checking_xray': 'Проверка Xray...',
            'msg_merging': 'Объединение...',
            'msg_upload_done': 'Подписка обновлена',
            'msg_no_results_upload': 'Нет результатов для отправки',
            'dialog_copy_title': 'Скопируйте ссылку',
            'dialog_copy_close': 'Закрыть',
            'dialog_copy_msg_linux': 'Установите wl-clipboard для автокопирования:\n[color=#8b5cf6]sudo apt install wl-clipboard[/color]',
            'dialog_copy_msg_android': 'Выделите текст в поле выше и скопируйте его вручную:',
            'unit_ms': 'мс.',
            'unit_pcs': 'шт.',
            'status_downloading': 'Скачивание...',
            'status_uploading': 'Загрузка...',
            'status_ok': 'ok',
            'status_pass': 'pass',
            'status_fail': 'fail',
            'cli_working': 'работающих',
            'cli_timeout': 'тайм-аут',
            'cli_not_found': 'Рабочих конфигов не найдено',
            'cli_summary': 'РЕЗУЛЬТАТЫ ТЕСТИРОВАНИЯ',
            'cli_task': 'Задача',
            'cli_found': 'Найдено',
            'cli_status': 'Статус',
            'cli_total_found': 'ИТОГО: Найдено {count} рабочих конфигов!',
            'cli_total_none': 'ИТОГО: Рабочих конфигов не найдено',
            'cli_ping': 'Пинг',
            'cli_config': 'Конфиг',
            'cli_menu_title': 'ГЛАВНОЕ МЕНЮ:',
            'cli_menu_full': 'Полный цикл (Скачать + Тест всех)',
            'cli_menu_download': 'Только скачать конфиги',
            'cli_menu_test_all': 'Протестировать всё (без скачивания)',
            'cli_menu_select_cat': 'Выбрать категорию для теста',
            'cli_menu_github': 'Отправить результаты на GitHub',
            'cli_menu_exit': 'Выход',
            'cli_choice': 'Выберите действие: ',
            'cli_press_enter': 'Нажмите Enter для продолжения...',
            'cli_source': 'Источник:',
            'cli_github_confirm': 'Отправить результаты в репозиторий? (y/n): ',
            'cli_success': 'Успешно!',
            'msg_user': 'Пользователь',
            'msg_guest': 'Гость',
            'dialog_update_sub': 'Обновить подписку?',
            'dialog_update_sub_text': 'Обновить вашу подписку на сервере?',
            'dialog_github': 'Обновить GitHub?',
            'dialog_github_text': 'Зафиксировать изменения в репозитории?',
            'btn_yes': 'Да',
            'btn_no': 'Нет',
            'msg_upload_failed': 'Обновление не удалось.',
            'msg_upload_retry_proxy': 'Можно попробовать ещё раз через следующий рабочий конфиг ({label}).',
            'msg_upload_retry_direct': 'Подключитесь к стабильной сети и повторите попытку.',
            'msg_last_error': 'Последняя ошибка:',
            'btn_retry': 'Повторить',
            'btn_config': 'Конфиг',
            'msg_upload_proxy_attempt': 'Прямая отправка не удалась, пробую через рабочий конфиг {label}',
            'msg_upload_proxy_try': 'Пробую проксированное обновление через конфиг {label}',
            'msg_merge_done': 'Все VPN конфиги объединены',
        },
        'en': {
            'app_title': 'arqParse',
            'app_subtitle': 'VPN Config Testing',
            'login': 'Login',
            'password': 'Password',
            'tab_login': 'Login',
            'tab_register': 'Register',
            'btn_login': 'Login',
            'btn_register': 'Sign Up',
            'btn_guest': 'Enter as Guest',
            'by_author': 'by ',
            'subscription': 'Subscription',
            'sub_url_hint': 'Link will appear after login',
            'btn_copy_sub': 'Copy Link',
            'bot_link_prefix': 'Apply Telegram proxy in bot ',
            'btn_start_test': 'Start Test',
            'btn_adv_settings': 'Advanced Settings',
            'btn_hide_settings': 'Hide Settings',
            'select_tasks': 'Select Tasks',
            'btn_download': 'Download',
            'btn_results': 'Results',
            'btn_skip': 'Skip',
            'btn_stop': 'Stop',
            'progress': 'Progress:',
            'ready': 'Ready',
            'event_log': 'Event Log',
            'log_started': 'arqParse started',
            'settings': 'Settings',
            'settings_general': 'General',
            'auto_update': 'Auto-update sources',
            'language': 'Language',
            'btn_save': 'Save',
            'btn_reset': 'Reset to Defaults',
            'categories': 'Categories',
            'btn_add_category': '+ Add Category',
            'cat_name': 'Category Name',
            'cat_type': 'Type:',
            'cat_sources': 'Sources (URL):',
            'btn_add_url': '+ Add URL',
            'cat_target': 'Target URL',
            'cat_max_ping': 'Max Ping:',
            'cat_min_count': 'Min Count:',
            'cat_profile': 'Profile Name',
            'btn_delete': 'Delete',
            'msg_saved': 'Saved',
            'msg_restored': 'Settings restored',
            'msg_logged_out': 'Logged out successfully',
            'msg_guest_active': 'Guest mode activated',
            'msg_login_min': 'Login min 3 characters',
            'msg_pass_min': 'Password min 6 characters',
            'msg_connecting': 'Connecting',
            'msg_registering': 'Registering',
            'msg_server_offline': 'Server offline',
            'msg_auth_success': 'Success',
            'msg_auth_error': 'Error:',
            'msg_sub_copied': 'Copied',
            'msg_sub_no_url': 'Link unavailable',
            'msg_sub_guest': 'Feature unavailable for guests',
            'msg_op_running': 'Operation already in progress',
            'msg_no_tasks': 'Select at least one task',
            'msg_test_started': 'Starting...',
            'msg_testing': 'Testing:',
            'msg_checking_configs': 'Checking config updates...',
            'msg_checking_xray': 'Checking Xray...',
            'msg_merging': 'Merging...',
            'msg_upload_done': 'Subscription updated',
            'msg_no_results_upload': 'No results to upload',
            'dialog_copy_title': 'Copy Link',
            'dialog_copy_close': 'Close',
            'dialog_copy_msg_linux': 'Install wl-clipboard for auto-copy:\n[color=#8b5cf6]sudo apt install wl-clipboard[/color]',
            'dialog_copy_msg_android': 'Select text in the field above and copy it manually:',
            'unit_ms': 'ms.',
            'unit_pcs': 'pcs.',
            'status_downloading': 'Downloading...',
            'status_uploading': 'Uploading...',
            'status_ok': 'ok',
            'status_pass': 'pass',
            'status_fail': 'fail',
            'cli_working': 'working',
            'cli_timeout': 'timeout',
            'cli_not_found': 'No working configs found',
            'cli_summary': 'TEST RESULTS',
            'cli_task': 'Task',
            'cli_found': 'Found',
            'cli_status': 'Status',
            'cli_total_found': 'TOTAL: Found {count} working configs!',
            'cli_total_none': 'TOTAL: No working configs found',
            'cli_ping': 'Ping',
            'cli_config': 'Config',
            'cli_menu_title': 'MAIN MENU:',
            'cli_menu_full': 'Full Cycle (Download + Test All)',
            'cli_menu_download': 'Download Only',
            'cli_menu_test_all': 'Test All (No Download)',
            'cli_menu_select_cat': 'Select Category to Test',
            'cli_menu_github': 'Push results to GitHub',
            'cli_menu_exit': 'Exit',
            'cli_choice': 'Choice: ',
            'cli_press_enter': 'Press Enter to continue...',
            'cli_source': 'Source:',
            'cli_github_confirm': 'Push results to repository? (y/n): ',
            'cli_success': 'Success!',
            'msg_user': 'User',
            'msg_guest': 'Guest',
            'dialog_update_sub': 'Update Subscription?',
            'dialog_update_sub_text': 'Sync your results with the server?',
            'dialog_github': 'Update GitHub?',
            'dialog_github_text': 'Commit changes to the repository?',
            'btn_yes': 'Yes',
            'btn_no': 'No',
            'msg_upload_failed': 'Update failed.',
            'msg_upload_retry_proxy': 'You can try again via the next working config ({label}).',
            'msg_upload_retry_direct': 'Connect to a stable network and try again.',
            'msg_last_error': 'Last error:',
            'btn_retry': 'Retry',
            'btn_config': 'Config',
            'msg_upload_proxy_attempt': 'Direct upload failed, trying via working config {label}',
            'msg_upload_proxy_try': 'Trying proxied update via config {label}',
            'msg_merge_done': 'All VPN configs merged',
        }
    }

    def __init__(self, lang='ru'):
        self.lang = lang

    @classmethod
    def get_instance(cls):
        if not cls._instance:
            from arqparse.utils.settings_manager import load_settings
            try:
                lang = load_settings().get("language", "ru")
            except Exception:
                lang = "ru"
            cls._instance = cls(lang)
        return cls._instance

    def set_lang(self, lang):
        if lang in self.LANGUAGES:
            self.lang = lang

    def translate(self, key, **kwargs):
        text = self.LANGUAGES.get(self.lang, {}).get(key, key)
        if kwargs:
            try:
                return text.format(**kwargs)
            except Exception:
                return text
        return text

def _(key, **kwargs):
    return Translator.get_instance().translate(key, **kwargs)
